// User types
export const GUEST = "GUEST";
export const REGISTERED = "REGISTERED";
export const PROFILED = "PROFILED";
export const SCHEDULED = "SCHEDULED";
export const GROUPED = "GROUPED";
export const MET = "MET";
export const INACTIVE = "INACTIVE";
export const DELETED = "DELETED";
export const ADMIN = "ADMIN";

// Contact preferences
export const SMS = "SMS";
export const EMAIL = "EMAIL";

// Time availability
export const TIMES = ['Morning', 'Lunch', 'Afternoon', 'Dinner', 'Night']

export const ACTIVITIES = ['Walk', 'Meal', 'Call']

// Categories
export const CATEGORIES = [
  "Animal lover",
  "Artist",
  "Athlete",
  "B2B enthusiast",
  "Biologist",
  "Biotech fanatic",
  "Blockchain enthusiast",
  "Blogger",
  "Choreographer",
  "Comedian",
  "Consumer product enthusiast",
  "Contrarian",
  "Creative writer",
  "Debator",
  "Dancer",
  "Designer",
  "Early bird",
  "Economist",
  "Entrepreneur",
  "Environmentalist",
  "Fashionista",
  "Filmmaker",
  "Fintech enthusiast",
  "Global citizen",
  "Gym rat",
  "History buff",
  "Investor",
  "Legislator",
  "ML/AI enthusiast",
  "Martial artist",
  "Math addict",
  "Mechanic",
  "Meditator",
  "Mental models lover",
  "Musician",
  "Nature frolicker",
  "Night owl",
  "Open-minded",
  "Philosopher",
  "Photographer",
  "Physical scientist",
  "Psychologist",
  "Roboticist",
  "Runner",
  "Self-improver",
  "Social scientist",
  "Space aficionado",
  "Social-justice",
  "Sustainability fanatic",
  "Traveller",
  "Veggie lover",
  "Venture capital enthusiast"
];

export const MAJORS = [
  ["AAS", "African American Studies"],
  ["AFS", "African Studies"],
  ["AMS", "American Studies"],
  ["ANT", "Anthropology"],
  ["AOS", "Atmospheric & Oceanic Sciences"],
  ["APC", "Appl and Computational Math"],
  ["ARA", "Arabic"],
  ["ARC", "Architecture"],
  ["ART", "Art and Archaeology"],
  ["AST", "Astrophysical Sciences"],
  ["ATL", "Atelier"],
  ["BCS", "Bosnian-Croatian-Serbian"],
  ["CBE", "Chemical and Biological Engr"],
  ["CEE", "Civil and Environmental Engr"],
  ["CGS", "Cognitive Science"],
  ["CHI", "Chinese"],
  ["CHM", "Chemistry"],
  ["CHV", "Center for Human Values"],
  ["CLA", "Classics"],
  ["CLG", "Classical Greek"],
  ["COM", "Comparative Literature"],
  ["COS", "Computer Science"],
  ["CTL", "Center for Teaching & Learning"],
  ["CWR", "Creative Writing"],
  ["CZE", "Czech"],
  ["DAN", "Dance"],
  ["EAS", "East Asian Studies"],
  ["ECO", "Economics"],
  ["ECS", "European Cultural Studies"],
  ["EEB", "Ecology and Evol Biology"],
  ["EGR", "Engineering"],
  ["ELE", "Electrical Engineering"],
  ["ENE", "Energy Studies"],
  ["ENG", "English"],
  ["ENT", "Entrepreneurship"],
  ["ENV", "Environmental Studies"],
  ["EPS", "Contemporary European Politics"],
  ["FIN", "Finance"],
  ["FRE", "French"],
  ["FRS", "Freshman Seminars"],
  ["GEO", "Geosciences"],
  ["GER", "German"],
  ["GHP", "Global Health & Health Policy"],
  ["GLS", "Global Seminar"],
  ["GSS", "Gender and Sexuality Studies"],
  ["HEB", "Hebrew"],
  ["HIN", "Hindi"],
  ["HIS", "History"],
  ["HLS", "Hellenic Studies"],
  ["HOS", "History of Science"],
  ["HUM", "Humanistic Studies"],
  ["ISC", "Integated Science Curriculum"],
  ["ITA", "Italian"],
  ["JDS", "Judaic Studies"],
  ["JPN", "Japanese"],
  ["JRN", "Journalism"],
  ["KOR", "Korean"],
  ["LAO", "Latino Studies"],
  ["LAS", "Latin American Studies"],
  ["LAT", "Latin"],
  ["LCA", "Lewis Center for the Arts"],
  ["LIN", "Linguistics"],
  ["MAE", "Mech and Aerospace Engr"],
  ["MAT", "Mathematics"],
  ["MED", "Medieval Studies"],
  ["MOD", "Media and Modernity"],
  ["MOG", "Modern Greek"],
  ["MOL", "Molecular Biology"],
  ["MSE", "Materials Science and Engr"],
  ["MTD", "Music Theater"],
  ["MUS", "Music"],
  ["NES", "Near Eastern Studies"],
  ["NEU", "Neuroscience"],
  ["ORF", "Oper Res and Financial Engr"],
  ["PAW", "Ancient World"],
  ["PER", "Persian"],
  ["PHI", "Philosophy"],
  ["PHY", "Physics"],
  ["PLS", "Polish"],
  ["POL", "Politics"],
  ["POP", "Population Studies"],
  ["POR", "Portuguese"],
  ["PSY", "Psychology"],
  ["QCB", "Quantitative Computational Bio"],
  ["REL", "Religion"],
  ["RES", "Russian, East Europ, Eurasian"],
  ["RUS", "Russian"],
  ["SAN", "Sanskrit"],
  ["SAS", "South Asian Studies"],
  ["SLA", "Slavic Languages and Lit"],
  ["SML", "Statistics & Machine Learning"],
  ["SOC", "Sociology"],
  ["SPA", "Spanish"],
  ["SPI", "School of Public and International Affairs"],
  ["STC", "Science and Technology Council"],
  ["SWA", "Swahili"],
  ["THR", "Theater"],
  ["TPP", "Teacher Preparation"],
  ["TRA", "Translation, Intercultural Com"],
  ["TUR", "Turkish"],
  ["TWI", "Twi"],
  ["URB", "Urban Studies"],
  ["URD", "Urdu"],
  ["VIS", "Visual Arts"],
  ["WRI", "Princeton Writing Program"]
]

export const MINORS = [
  "African American Studies",
  "African Studies",
  "American Studies",
  "Applications of Computing",
  "Applied and Computational Mathematics",
  "Archaeology",
  "Architecture and Engineering",
  "Asian American Studies",
  "Biophysics",
  "Cognitive Science",
  "Contemporary European Politics and Society",
  "Creative Writing",
  "Dance",
  "East Asian Studies",
  "Engineering and Management Systems",
  "Engineering Biology",
  "Engineering Physics",
  "Entrepreneurship",
  "Environmental Studies",
  "Ethnographic Studies",
  "European Cultural Studies",
  "Finance",
  "Gender and Sexuality Studies",
  "Geological Engineering",
  "Global Health and Health Policy",
  "Hellenic Studies",
  "History and the Practice of Diplomacy",
  "Humanistic Studies",
  "Jazz Studies",
  "Journalism",
  "Judaic Studies",
  "Language and Culture",
  "Latin American Studies",
  "Latino Studies",
  "Linguistics",
  "Materials Science and Engineering",
  "Medieval Studies",
  "Music Performance",
  "Music Theater",
  "Near Eastern Studies",
  "Neuroscience",
  "Planets and Life",
  "Quantitative and Computational Biology",
  "Robotics and Intelligent Systems",
  "Russian, East European and Eurasian Studies",
  "South Asian Studies",
  "Statistics and Machine Learning",
  "Sustainable Energy",
  "Teacher Preparation",
  "Technology and Society",
  "Theater",
  "Translation and Intercultural Communication",
  "Urban Studies",
  "Values and Public Life",
  "Visual Arts"
]
